### ISSUE TITLE
DIA schedule

### ISSUE THREAD

**Issue by eszcloud** [loudnate/Loop#113] opened 2016-08-09 19:26 UTC
Allow different DIAs throughout the day as a function of time (e.g. 12 m - 8 am DIA = 5; 8 am - 10 pm DIA = 4; 10 pm - 11:59:59 pm DIA = 5).

**Comment by loudnate** [comment] 2016-08-20 17:34
This is a duplicate of https://github.com/loudnate/LoopKit/issues/20. Thanks!

**Closed by loudnate** 2016-08-20 17:34 UTC
Labels: duplicate
